# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
apt_packages:
  - libudunits2-dev
# Since udunits2 library has to be installed outside R environment, so travis will not
# have it by default, have to install it manually, ggforce and other packages with dependency units
# will have the same issue.
dist: precise

